nombre=input("cual es tu nombre: ")
apellido=input("cual es tu apellido: ")
id1=input("id 1: ")
gasto1=input("gasto 1: ")
costo_de_gasto1=float(input("costo de gasto 1: "))
id2=input("id 2: ")
gasto2=input("gasto 2: ")
costo_de_gasto2=float(input("costo de gasto 2: "))
id3=input("id 3: ")
gasto3=input("gasto 3: ")
costo_de_gasto3=float(input("costo de gasto 3: "))
id4=input("id 4: ")
gasto4=input("gasto 4: ")
costo_de_gasto4=float(input("costo de gasto 4: "))
id5=input("id 5: ")
gasto5=input("gasto 5: ")
costo_de_gasto5=float(input("costo de gasto 5: "))

print("registro de egresos de: {0} {1} ".format(nombre,apellido))
print("\"Id\"---\"Descripcion\"\t---\"Monto\"")
print("{:>5s}---{:<20s}---${:7.2f}".format(id1,gasto1,costo_de_gasto1))
print("{:>5s}---{:<20s}---${:7.2f}".format(id2,gasto2,costo_de_gasto2))
print("{:>5s}---{:<20s}---${:7.2f}".format(id3,gasto3,costo_de_gasto3))
print("{:>5s}---{:<20s}---${:7.2f}".format(id4,gasto4,costo_de_gasto4))
print("{:>5s}---{:<20s}---${:7.2f}".format(id5,gasto5,costo_de_gasto5))


